apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-host.fullname" . }}
  labels:
    {{- include "simple-host.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "simple-host.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
          {{- if .Values.networkAttachment.config }}
          k8s.v1.cni.cncf.io/networks: {{ include "simple-host.fullname" . }}
          {{- end }}
          {{- with .Values.podAnnotations -}}
          {{- toYaml .Values.podAnnotations | nindent 8 }}
          {{- end }}
      labels:
        {{- include "simple-host.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
