{{- if .Values.networkAttachment.config }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "simple-host.fullname" . }}
spec:
  config: {{ .Values.networkAttachment.config | quote }}
{{- end }}

