# Default values for aws-overlay-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

xrd1:
  # Image configuration
  image:
    # repository:
    pullPolicy: Always
    #tag: ""
  resources:
    limits:
      memory: 8Gi
      hugepages-1Gi: 3Gi
  securityContext:
    privileged: true
  nodeSelector:
      xrd.node: nodeA
  persistence:
    enabled: true
    size: "6Gi"
    accessModes:
    - ReadWriteOnce
    storageClass: "gp2"
  config:
    # ASCII XR configuration to be applied on XR boot.
    ascii: |
      hostname xrd1
      logging console debugging
      logging monitor debugging
      vrf nfs
       address-family ipv4 unicast
        import route-target
         100:100
        !
        export route-target
         100:100
        !
       !
      !
      line default
       exec-timeout 0 0
       width 0
       length 0
      !
      bfd
       multipath include location 0/RP0/CPU0
       echo disable
      !
      call-home
       service active
       contact smart-licensing
       profile CiscoTAC-1
        active
        destination transport-method email disable
        destination transport-method http
       !
      !
      interface Loopback0
       ipv4 address 1.0.0.11 255.255.255.255
      !
      interface tunnel-ip1
       mtu 1450
       ipv4 address 10.1.2.11 255.255.255.0
       tunnel source 10.0.2.11
       tunnel destination 10.0.2.12
       logging events link-status
      !
      interface tunnel-ip2
       mtu 1450
       ipv4 address 10.1.3.11 255.255.255.0
       tunnel source 10.0.3.11
       tunnel destination 10.0.3.12
       logging events link-status
      !
      interface HundredGigE0/0/0/0
       vrf nfs
       ipv4 address 10.0.1.11 255.255.255.0
      !
      interface HundredGigE0/0/0/1
       ipv4 address 10.0.2.11 255.255.255.0
      !
      interface HundredGigE0/0/0/2
       ipv4 address 10.0.3.11 255.255.255.0
      !
      router isis 1
       is-type level-2-only
       net 49.0000.0000.0011.00
       log adjacency changes
       lsp-mtu 1400
       address-family ipv4 unicast
        metric-style wide
        advertise link attributes
        segment-routing mpls
       !
       interface Loopback0
        address-family ipv4 unicast
         prefix-sid index 11
        !
       !
       interface tunnel-ip1
        point-to-point
        address-family ipv4 unicast
        !
       !
       interface tunnel-ip2
        point-to-point
        address-family ipv4 unicast
        !
       !
      !
      router bgp 100
       bfd minimum-interval 100
       bgp router-id 1.0.0.11
       bgp update-delay 0
       address-family vpnv4 unicast
       !
       neighbor 1.0.0.12
        remote-as 100
        bfd fast-detect
        update-source Loopback0
        address-family vpnv4 unicast
        !
       !
       vrf nfs
        rd auto
        address-family ipv4 unicast
         redistribute connected
        !
       !
      !
      segment-routing
      !
    asciiEveryBoot: True
  interfaces:
    - type: pci
      config:
        last: 3
  pciDriver: "igb_uio"
  cpu:
    cpuset: 2-3
xrd2:
  # Image configuration
  image:
    # repository:
    pullPolicy: Always
    #tag: ""
  resources:
    limits:
      memory: 8Gi
      hugepages-1Gi: 3Gi
  securityContext:
    privileged: true
  nodeSelector:
      xrd.node: nodeB
  persistence:
    enabled: true
    size: "6Gi"
    accessModes:
    - ReadWriteOnce
    storageClass: "gp2"
  config:
    # ASCII XR configuration to be applied on XR boot.
    ascii: |
      hostname xrd2
      logging console debugging
      logging monitor debugging
      vrf nfs
       address-family ipv4 unicast
        import route-target
         100:100
        !
        export route-target
         100:100
        !
       !
      !
      line default
       exec-timeout 0 0
       width 0
       length 0
      !
      bfd
       multipath include location 0/RP0/CPU0
       echo disable
      !
      call-home
       service active
       contact smart-licensing
       profile CiscoTAC-1
        active
        destination transport-method email disable
        destination transport-method http
       !
      !
      interface Loopback0
       ipv4 address 1.0.0.12 255.255.255.255
      !
      interface tunnel-ip1
       mtu 1450
       ipv4 address 10.1.2.12 255.255.255.0
       tunnel source 10.0.2.12
       tunnel destination 10.0.2.11
       logging events link-status
      !
      interface tunnel-ip2
       mtu 1450
       ipv4 address 10.1.3.12 255.255.255.0
       tunnel source 10.0.3.12
       tunnel destination 10.0.3.11
       logging events link-status
      !
      interface HundredGigE0/0/0/0
       vrf nfs
       ipv4 address 10.0.4.12 255.255.255.0
      !
      interface HundredGigE0/0/0/1
       ipv4 address 10.0.2.12 255.255.255.0
      !
      interface HundredGigE0/0/0/2
       ipv4 address 10.0.3.12 255.255.255.0
      !
      router isis 1
       is-type level-2-only
       net 49.0000.0000.0012.00
       log adjacency changes
       lsp-mtu 1400
       address-family ipv4 unicast
        metric-style wide
        advertise link attributes
        segment-routing mpls
       !
       interface Loopback0
        address-family ipv4 unicast
         prefix-sid index 12
        !
       !
       interface tunnel-ip1
        point-to-point
        address-family ipv4 unicast
        !
       !
       interface tunnel-ip2
        point-to-point
        address-family ipv4 unicast
        !
       !
      !
      router bgp 100
       bfd minimum-interval 100
       bgp router-id 1.0.0.12
       bgp update-delay 0
       address-family vpnv4 unicast
       !
       neighbor 1.0.0.11
        remote-as 100
        bfd fast-detect
        update-source Loopback0
        address-family vpnv4 unicast
        !
       !
       vrf nfs
        rd auto
        address-family ipv4 unicast
         redistribute connected
        !
       !
      !
      segment-routing
      !
    asciiEveryBoot: True
  interfaces:
  - type: pci
    config:
      last: 3
  pciDriver: "igb_uio"
  cpu:
    cpuset: 2-3

host1:
  image:
    repository: alpine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  networkAttachment:
    config: '{
        "cniVersion": "0.3.1",
        "type": "host-device",
        "device": "eth1",
        "ipam": {
          "type": "static",
          "addresses" : [
              {
                  "address": "10.0.1.10/24",
                  "gateway": "10.0.1.11"
              }
          ],
          "routes" : [
              {
                  "dst": "10.0.4.0/24"
              }
          ]
        }
      }'

  nodeSelector:
    xrd.node: nodeC

host2:
  image:
    repository: alpine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  networkAttachment:
    config: '{
        "cniVersion": "0.3.1",
        "type": "host-device",
        "device": "eth2",
        "ipam": {
          "type": "static",
          "addresses" : [
              {
                  "address": "10.0.4.10/24",
                  "gateway": "10.0.4.12"
              }
          ],
          "routes" : [
              {
                  "dst": "10.0.1.0/24"
              }
          ]
        }
      }'

  nodeSelector:
    xrd.node: nodeC
