AWSTemplateFormatVersion: "2010-09-09"
Description: EKS stack for running XRd topologies, including creating VPC
# Composite of xrd-vpc and xrd-eks-existing-vpc


Metadata:
  cfn-lint:
    config:
      ignore_checks:
        # AWSQS::Kubernetes::Resource not found during Lint (due to custom activation?)
        - E3001
  LintSpellExclude:
    - Multus

Parameters:

  # Parameters from xrd-vpc
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String

  AvailabilityZones:
    Description: 'List of precisely 2 Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>

  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.101.0/24
    Description: CIDR block for private subnet 1A located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.102.0/24
    Description: CIDR block for private subnet 2A located in Availability Zone 2
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.111.0/24
    Description: CIDR block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.112.0/24
    Description: CIDR block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String

  XrdSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for first XRd subnet
    Type: String
    Default: "10.0.1.0/24"

  XrdSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 2nd XRd subnet
    Type: String
    Default: "10.0.2.0/24"

  XrdSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for third XRd subnet
    Type: String
    Default: "10.0.3.0/24"

  XrdSubnet4CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 4th XRd subnet
    Type: String
    Default: "10.0.4.0/24"

  XrdSubnet5CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 5th XRd subnet
    Type: String
    Default: "10.0.5.0/24"

  XrdSubnet6CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 6th XRd subnet
    Type: String
    Default: "10.0.6.0/24"


  # Parameters from xrd-eks-existing-vpc
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: CIDR IP range that is permitted to access the instances. We recommend that you set this value to a trusted IP range.
    Type: String
  EKSPublicAccessEndpoint:
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
    Description: Configure access to the Kubernetes API server endpoint from outside of your VPC.

  AdditionalEKSAdminUserArn:
    Default: ""
    AllowedPattern: '^arn:(aws|aws-cn|aws-us-gov):iam::[0-9]{12}:.*|^$'
    Description: "(Optional) IAM user Amazon Resource Name (ARN) to be granted administrative access to the EKS cluster."
    Type: String
  AdditionalEKSAdminRoleArn:
    Default: ""
    AllowedPattern: '^arn:(aws|aws-cn|aws-us-gov):iam::[0-9]{12}:.*|^$'
    Description: "(Optional) IAM role Amazon Resource Name (ARN) to be granted administrative access to the EKS cluster."
    Type: String

  KeyPairName:
    Description: Name of an existing key pair, which allows you
      to securely connect to your instance after it launches.
    Type: "AWS::EC2::KeyPair::KeyName"

  EKSClusterName:
    Type: String
    Default: "xrd-cluster"
    Description: "Name for the EKS cluster"

  MultusCNI:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: Skip enabling Multus CNI by choosing "Disabled".

  MultusCNIManifestURL:
    Default: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/multus/v3.7.2-eksbuild.1/aws-k8s-multus.yaml
    Description: "URL containing multus manifest (default v3.7.2)"
    Type: String

  KubernetesVersion:
    Type: String
    AllowedValues: [ "1.22", "1.23", "1.24" ]
    Default: "1.22"
    Description: Kubernetes control plane version.

  EKSAdvancedConfigurationName:
    Default: XrdEksAdvancedConfiguration
    Type: String
    Description: "(Optional) Name of EKS Advanced Configuration table"


  # Parameters specific to this template (rather than nested template)
  XrdS3BucketName:
    # Default: TBD
    Type: String
  XrdS3KeyPrefix:
    # Default: TBD
    Type: String
  XrdS3BucketRegion:
    # Default: TBD
    Type: String

Conditions:
  XrdSubnet1Required: !Not [ !Equals [ !Ref XrdSubnet1CIDR, '' ] ]
  XrdSubnet2Required: !Not [ !Equals [ !Ref XrdSubnet2CIDR, '' ] ]
  XrdSubnet3Required: !Not [ !Equals [ !Ref XrdSubnet3CIDR, '' ] ]
  XrdSubnet4Required: !Not [ !Equals [ !Ref XrdSubnet4CIDR, '' ] ]
  XrdSubnet5Required: !Not [ !Equals [ !Ref XrdSubnet5CIDR, '' ] ]
  XrdSubnet6Required: !Not [ !Equals [ !Ref XrdSubnet6CIDR, '' ] ]

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub https://${XrdS3BucketName}.s3.${XrdS3BucketRegion}.${AWS::URLSuffix}/${XrdS3KeyPrefix}cf-templates/xrd-vpc-cf.yaml
      Parameters:
        VPCCIDR: !Ref VPCCIDR
        AvailabilityZones: !Join [",", !Ref AvailabilityZones]
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        XrdSubnet1CIDR: !Ref XrdSubnet1CIDR
        XrdSubnet2CIDR: !Ref XrdSubnet2CIDR
        XrdSubnet3CIDR: !Ref XrdSubnet3CIDR
        XrdSubnet4CIDR: !Ref XrdSubnet4CIDR
        XrdSubnet5CIDR: !Ref XrdSubnet5CIDR
        XrdSubnet6CIDR: !Ref XrdSubnet6CIDR

  EKSStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub https://${XrdS3BucketName}.s3.${XrdS3BucketRegion}.${AWS::URLSuffix}/${XrdS3KeyPrefix}cf-templates/xrd-eks-existing-vpc-cf.yaml
      Parameters:
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        EKSPublicAccessEndpoint: !Ref EKSPublicAccessEndpoint
        AdditionalEKSAdminUserArn: !Ref AdditionalEKSAdminUserArn
        AdditionalEKSAdminRoleArn: !Ref AdditionalEKSAdminRoleArn
        KeyPairName: !Ref KeyPairName
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1ID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2ID
        EKSClusterName: !Ref EKSClusterName
        MultusCNI: !Ref MultusCNI
        MultusCNIManifestURL: !Ref MultusCNIManifestURL
        KubernetesVersion: !Ref KubernetesVersion
        EKSAdvancedConfigurationName: !Ref EKSAdvancedConfigurationName


Outputs:
  VPCID:
    Value: !GetAtt VPCStack.Outputs.VPCID
    Description: "VPC ID"

  PrivateSubnet1ID:
    Description: Private subnet within the primary (first) AZ
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1ID

  PrivateSubnet2ID:
    Description: Private subnet within the secondary (unused) AZ
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2ID

  PublicSubnet1ID:
    Description: Public subnet within the primary (first) AZ
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1ID

  PublicSubnet2ID:
    Description: Public subnet within the secondary (unused) AZ
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2ID

  XrdSubnet1ID:
    Description: 1st Xrd subnet
    Condition: XrdSubnet1Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet1ID

  XrdSubnet2ID:
    Description: 2nd Xrd subnet
    Condition: XrdSubnet2Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet2ID

  XrdSubnet3ID:
    Description: 3rd Xrd subnet
    Condition: XrdSubnet3Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet3ID

  XrdSubnet4ID:
    Description: 4th Xrd subnet
    Condition: XrdSubnet4Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet4ID

  XrdSubnet5ID:
    Description: 5th Xrd subnet
    Condition: XrdSubnet5Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet5ID

  XrdSubnet6ID:
    Description: 6th Xrd subnet
    Condition: XrdSubnet6Required
    Value: !GetAtt VPCStack.Outputs.XrdSubnet6ID

  EKSClusterName:
    Value: !GetAtt EKSStack.Outputs.EKSClusterName
  BastionIP:
    Value: !GetAtt EKSStack.Outputs.BastionIP
  BastionSecurityGroup:
    Value: !GetAtt EKSStack.Outputs.BastionSecurityGroup
  NodeGroupSecurityGroup:
    Value: !GetAtt EKSStack.Outputs.NodeGroupSecurityGroup
  ControlPlaneSecurityGroup:
    Value: !GetAtt EKSStack.Outputs.ControlPlaneSecurityGroup
  OIDCIssuerURL:
    Value: !GetAtt EKSStack.Outputs.OIDCIssuerURL
