---
AWSTemplateFormatVersion: "2010-09-09"
Description: VPC suitable for running XRd topologies.

#Metadata:

Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String

  AvailabilityZones:
    Description: 'List of precisely 2 Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>

  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.101.0/24
    Description: CIDR block for private subnet 1A located in Availability Zone 1
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.102.0/24
    Description: CIDR block for private subnet 2A located in Availability Zone 2
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.111.0/24
    Description: CIDR block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.112.0/24
    Description: CIDR block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String

  XrdSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for first XRd subnet
    Type: String
    Default: "10.0.1.0/24"
  XrdSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 2nd XRd subnet
    Type: String
    Default: "10.0.2.0/24"
  XrdSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for third XRd subnet
    Type: String
    Default: "10.0.3.0/24"
  XrdSubnet4CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 4th XRd subnet
    Type: String
    Default: "10.0.4.0/24"
  XrdSubnet5CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 5th XRd subnet
    Type: String
    Default: "10.0.5.0/24"
  XrdSubnet6CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 6th XRd subnet
    Type: String
    Default: "10.0.6.0/24"
  XrdSubnet7CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 7th XRd subnet
    Type: String
    Default: "10.0.7.0/24"
  XrdSubnet8CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 8th XRd subnet
    Type: String
    Default: "10.0.8.0/24"
  XrdSubnet9CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 9th XRd subnet
    Type: String
    Default: "10.0.9.0/24"
  XrdSubnet10CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 10th XRd subnet
    Type: String
    Default: "10.0.10.0/24"
  XrdSubnet11CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 11th XRd subnet
    Type: String
    Default: "10.0.11.0/24"
  XrdSubnet12CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 12th XRd subnet
    Type: String
    Default: "10.0.12.0/24"
  XrdSubnet13CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 13th XRd subnet
    Type: String
    Default: "10.0.13.0/24"
  XrdSubnet14CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: (Optional) CIDR for 14th XRd subnet
    Type: String
    Default: "10.0.14.0/24"

  # XrdS3BucketName:
  #   # Default: TBD
  #   Type: String
  # XrdS3KeyPrefix:
  #   # Default: TBD
  #   Type: String
  # XrdS3BucketRegion:
  #   # Default: TBD
  #   Type: String


Conditions:
  XrdSubnet1Required: !Not [ !Equals [ !Ref XrdSubnet1CIDR, '' ] ]
  XrdSubnet2Required: !Not [ !Equals [ !Ref XrdSubnet2CIDR, '' ] ]
  XrdSubnet3Required: !Not [ !Equals [ !Ref XrdSubnet3CIDR, '' ] ]
  XrdSubnet4Required: !Not [ !Equals [ !Ref XrdSubnet4CIDR, '' ] ]
  XrdSubnet5Required: !Not [ !Equals [ !Ref XrdSubnet5CIDR, '' ] ]
  XrdSubnet6Required: !Not [ !Equals [ !Ref XrdSubnet6CIDR, '' ] ]
  XrdSubnet7Required: !Not [ !Equals [ !Ref XrdSubnet7CIDR, '' ] ]
  XrdSubnet8Required: !Not [ !Equals [ !Ref XrdSubnet8CIDR, '' ] ]
  XrdSubnet9Required: !Not [ !Equals [ !Ref XrdSubnet9CIDR, '' ] ]
  XrdSubnet10Required: !Not [ !Equals [ !Ref XrdSubnet10CIDR, '' ] ]
  XrdSubnet11Required: !Not [ !Equals [ !Ref XrdSubnet11CIDR, '' ] ]
  XrdSubnet12Required: !Not [ !Equals [ !Ref XrdSubnet12CIDR, '' ] ]
  XrdSubnet13Required: !Not [ !Equals [ !Ref XrdSubnet13CIDR, '' ] ]
  XrdSubnet14Required: !Not [ !Equals [ !Ref XrdSubnet14CIDR, '' ] ]

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

    Metadata:
      cfn-lint: { config: { ignore_checks: [ W9901 ] } }
    Properties:
      #TemplateURL: !Sub 'https://${XrdS3BucketName}.s3.${XrdS3BucketRegion}.${AWS::URLSuffix}/${XrdS3KeyPrefix}submodules/quickstart-amazon-eks/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
      TemplateURL: https://s3.amazonaws.com/aws-quickstart/quickstart-aws-vpc/templates/aws-vpc.template.yaml

      Parameters:
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        NumberOfAZs: 2
        PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1CIDR'
        PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2CIDR'
        PrivateSubnetATag2: "kubernetes.io/role/internal-elb="
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        PublicSubnetTag2: "kubernetes.io/role/elb="
        VPCCIDR: !Ref 'VPCCIDR'

  XrdSubnet1:
    Condition: XrdSubnet1Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet1CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 1
        - Key: cisco.xrd.subnet
          Value: 1
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet2:
    Condition: XrdSubnet2Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet2CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 2
        - Key: cisco.xrd.subnet
          Value: 2
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet3:
    Condition: XrdSubnet3Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet3CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 3
        - Key: cisco.xrd.subnet
          Value: 3
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet4:
    Condition: XrdSubnet4Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet4CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 4
        - Key: cisco.xrd.subnet
          Value: 4
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet5:
    Condition: XrdSubnet5Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet5CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 5
        - Key: cisco.xrd.subnet
          Value: 5
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet6:
    Condition: XrdSubnet6Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet6CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 6
        - Key: cisco.xrd.subnet
          Value: 6
      VpcId: !GetAtt VPCStack.Outputs.VPCID

  XrdSubnet7:
    Condition: XrdSubnet7Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet7CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 7
        - Key: cisco.xrd.subnet
          Value: 7
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet8:
    Condition: XrdSubnet8Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet8CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 8
        - Key: cisco.xrd.subnet
          Value: 8
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet9:
    Condition: XrdSubnet9Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet9CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 9
        - Key: cisco.xrd.subnet
          Value: 9
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet10:
    Condition: XrdSubnet10Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet10CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 10
        - Key: cisco.xrd.subnet
          Value: 10
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet11:
    Condition: XrdSubnet11Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet11CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 11
        - Key: cisco.xrd.subnet
          Value: 11
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet12:
    Condition: XrdSubnet12Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet12CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 12
        - Key: cisco.xrd.subnet
          Value: 12
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet13:
    Condition: XrdSubnet13Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet13CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 13
        - Key: cisco.xrd.subnet
          Value: 13
      VpcId: !GetAtt VPCStack.Outputs.VPCID
  XrdSubnet14:
    Condition: XrdSubnet14Required
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref XrdSubnet14CIDR
      Tags:
        - Key: Name
          Value: XRd subnet 14
        - Key: cisco.xrd.subnet
          Value: 14
      VpcId: !GetAtt VPCStack.Outputs.VPCID

Outputs:
  VPCID:
    Value: !GetAtt VPCStack.Outputs.VPCID
    Description: "VPC ID"

  PrivateSubnet1ID:
    Description: Private subnet within the primary (first) AZ
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1AID

  PrivateSubnet2ID:
    Description: Private subnet within the secondary (unused) AZ
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2AID

  PublicSubnet1ID:
    Description: Public subnet within the primary (first) AZ
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1ID

  PublicSubnet2ID:
    Description: Public subnet within the secondary (unused) AZ
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2ID

  XrdSubnet1ID:
    Description: 1st Xrd subnet
    Condition: XrdSubnet1Required
    Value: !GetAtt XrdSubnet1.SubnetId

  XrdSubnet2ID:
    Description: 2nd Xrd subnet
    Condition: XrdSubnet2Required
    Value: !GetAtt XrdSubnet2.SubnetId

  XrdSubnet3ID:
    Description: 3rd Xrd subnet
    Condition: XrdSubnet3Required
    Value: !GetAtt XrdSubnet3.SubnetId

  XrdSubnet4ID:
    Description: 4th Xrd subnet
    Condition: XrdSubnet4Required
    Value: !GetAtt XrdSubnet4.SubnetId

  XrdSubnet5ID:
    Description: 5th Xrd subnet
    Condition: XrdSubnet5Required
    Value: !GetAtt XrdSubnet5.SubnetId

  XrdSubnet6ID:
    Description: 6th Xrd subnet
    Condition: XrdSubnet6Required
    Value: !GetAtt XrdSubnet6.SubnetId

  XrdSubnet7ID:
    Description: 7th Xrd subnet
    Condition: XrdSubnet7Required
    Value: !GetAtt XrdSubnet7.SubnetId
  XrdSubnet8ID:
    Description: 8th Xrd subnet
    Condition: XrdSubnet8Required
    Value: !GetAtt XrdSubnet8.SubnetId
  XrdSubnet9ID:
    Description: 9th Xrd subnet
    Condition: XrdSubnet9Required
    Value: !GetAtt XrdSubnet9.SubnetId
  XrdSubnet10ID:
    Description: 10th Xrd subnet
    Condition: XrdSubnet10Required
    Value: !GetAtt XrdSubnet10.SubnetId
  XrdSubnet11ID:
    Description: 11th Xrd subnet
    Condition: XrdSubnet11Required
    Value: !GetAtt XrdSubnet11.SubnetId
  XrdSubnet12ID:
    Description: 12th Xrd subnet
    Condition: XrdSubnet12Required
    Value: !GetAtt XrdSubnet12.SubnetId
  XrdSubnet13ID:
    Description: 13th Xrd subnet
    Condition: XrdSubnet13Required
    Value: !GetAtt XrdSubnet13.SubnetId
  XrdSubnet14ID:
    Description: 14th Xrd subnet
    Condition: XrdSubnet14Required
    Value: !GetAtt XrdSubnet14.SubnetId

